import { Tray, Menu, nativeImage, BrowserWindow, ipcMain, app } from 'electron';
import { getConfig, saveConfig, applyLoginItem } from './config';
import { t, resetUILanguage } from './i18n';
import * as path from 'path';

let tray: Tray | null = null;
let settingsWin: BrowserWindow | null = null;

let onTranslateCallback: (() => void) | null = null;
let onHideCallback: (() => void) | null = null;
let onClearCacheCallback: (() => void) | null = null;
let onSelectionTranslateCallback: (() => void) | null = null;
let onClipboardTranslateCallback: (() => void) | null = null;
let isOverlayVisibleFn: (() => boolean) | null = null;

export function setTranslateCallback(cb: () => void) {
  onTranslateCallback = cb;
}

export function setHideCallback(cb: () => void) {
  onHideCallback = cb;
}

export function setClearCacheCallback(cb: () => void) {
  onClearCacheCallback = cb;
}

export function setSelectionTranslateCallback(cb: () => void) {
  onSelectionTranslateCallback = cb;
}

export function setClipboardTranslateCallback(cb: () => void) {
  onClipboardTranslateCallback = cb;
}

export function setOverlayVisibleFn(fn: () => boolean) {
  isOverlayVisibleFn = fn;
}

/// 菜单栏图标：32x32 的鹦鹉剪影，按 2x 载入，也就是 16pt。
const TRAY_ICON_BASE64 =
  'iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAWfmNhQlgAABZ+anVtYgAAAB5qdW1kYzJwYQARABCAAACqADibcQNjMnBhAAAAFlhqdW1iAAAAR2p1bWRjMm1hABEAEIAAAKoAOJtxA3VybjpjMnBhOmIxMWJjOGZkLWUwZjMtNDY4MC05NjQ3LTVkOGFkN2NkNmVjYwAAAAOTanVtYgAAAClqdW1kYzJhcwARABCAAACqADibcQNjMnBhLmFzc2VydGlvbnMAAAAAuGp1bWIAAABEanVtZGNib3IAEQAQgAAAqgA4m3ETYzJwYS5pbmdyZWRpZW50LnYzAAAAABhjMnNoKmG5mvWg7sn5JDiqLc012gAAAGxjYm9yo2lkYzpmb3JtYXRpaW1hZ2UvcG5namluc3RhbmNlSUR4LHhtcDppaWQ6MmZhNGZmNWEtNTAwNS00NmVmLWE5YzEtZjMwMzhiNWJhOWI0bHJlbGF0aW9uc2hpcGhwYXJlbnRPZgAAAeJqdW1iAAAAQWp1bWRjYm9yABEAEIAAAKoAOJtxE2MycGEuYWN0aW9ucy52MgAAAAAYYzJzaAdy923hmtm5QoTPbX1Nx4MAAAGZY2JvcqJnYWN0aW9uc4KiZmFjdGlvbmtjMnBhLm9wZW5lZGpwYXJhbWV0ZXJzoWtpbmdyZWRpZW50c4GiY3VybHgtc2VsZiNqdW1iZj1jMnBhLmFzc2VydGlvbnMvYzJwYS5pbmdyZWRpZW50LnYzZGhhc2hYIB3uYs9V1Rvg8slcPL+7QuAXR2fWC0zew2x3gholJjLQpGZhY3Rpb254HWNvbS5hbnRocm9waWMuY2xhdWRlLnByb3ZpZGVkanBhcmFtZXRlcnOheB9jb20uYW50aHJvcGljLm9yaWdpbi1jb25maWRlbmNlZ3Vua25vd25rZGVzY3JpcHRpb254ZkNsYXVkZSBwcm92aWRlZCB0aGlzIGZpbGUgYXQgdGhlIHJlcXVlc3Qgb2YgYSB1c2VyIGFuZCBtYXkgaGF2ZSBjcmVhdGVkIG9yIG1vZGlmaWVkIHRoZSBmaWxlIGNvbnRlbnRzLm1zb2Z0d2FyZUFnZW50oWRuYW1lZkNsYXVkZXJhbGxBY3Rpb25zSW5jbHVkZWT1AAAAyGp1bWIAAABAanVtZGNib3IAEQAQgAAAqgA4m3ETYzJwYS5oYXNoLmRhdGEAAAAAGGMyc2jABM9kfWaHM42AwQ8/+b44AAAAgGNib3KlY2FsZ2ZzaGEyNTZjcGFkTQAAAAAAAAAAAAAAAABkaGFzaFggnnVRRNwVPeeE6zV+eUu0eGOplO1NCvi5eAr7usV1S2ZkbmFtZW5qdW1iZiBtYW5pZmVzdGpleGNsdXNpb25zgaJlc3RhcnQYIWZsZW5ndGgZFooAAAI+anVtYgAAACdqdW1kYzJjbAARABCAAACqADibcQNjMnBhLmNsYWltLnYyAAAAAg9jYm9ypWNhbGdmc2hhMjU2aXNpZ25hdHVyZXhNc2VsZiNqdW1iZj0vYzJwYS91cm46YzJwYTpiMTFiYzhmZC1lMGYzLTQ2ODAtOTY0Ny01ZDhhZDdjZDZlY2MvYzJwYS5zaWduYXR1cmVqaW5zdGFuY2VJRHgseG1wOmlpZDplMjVmODIyMS05NjM3LTRmM2UtYjZmNy00MGYwZWMzMjIzMTNyY3JlYXRlZF9hc3NlcnRpb25zg6JjdXJseC1zZWxmI2p1bWJmPWMycGEuYXNzZXJ0aW9ucy9jMnBhLmluZ3JlZGllbnQudjNkaGFzaFggHe5iz1XVG+DyyVw8v7tC4BdHZ9YLTN7DbHeCGiUmMtCiY3VybHgqc2VsZiNqdW1iZj1jMnBhLmFzc2VydGlvbnMvYzJwYS5hY3Rpb25zLnYyZGhhc2hYIKpuQlozdvs9xKuBtrOgID1w7N1CEbdBWLogl/vfPRMWomN1cmx4KXNlbGYjanVtYmY9YzJwYS5hc3NlcnRpb25zL2MycGEuaGFzaC5kYXRhZGhhc2hYINLd5lz/112dzhehGE2T+CmzTdkBK9j16nz/PHqJtsSAdGNsYWltX2dlbmVyYXRvcl9pbmZvo2RuYW1lb0FudGhyb3BpYyBGaWxlc2d2ZXJzaW9uZTEuMC4wa3NwZWNWZXJzaW9uZTIuNC4wAAAQOGp1bWIAAAAoanVtZGMyY3MAEQAQgAAAqgA4m3EDYzJwYS5zaWduYXR1cmUAAAAQCGNib3LShFkCEqIBJhghWQIKMIICBjCCAY2gAwIBAgIUQOWgCu7COdC+uIP6BkIFPWdVEwAwCgYIKoZIzj0EAwMwSTEXMBUGA1UEChMOQW50aHJvcGljLCBQQkMxLjAsBgNVBAMTJUFudGhyb3BpYyBDb250ZW50IENyZWRlbnRpYWxzIFJvb3QgQ0EwHhcNMjYwODA3MTg0MzU2WhcNMjgwODA2MTk0MzU2WjBEMRcwFQYDVQQKEw5BbnRocm9waWMsIFBCQzEpMCcGA1UEAxMgQW50aHJvcGljIENsYXVkZSBDb250ZW50IFNpZ25pbmcwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAASYegpry1AYBRTVNL1CpTlbROnY3dey+UrsF9C3phYrATN3ZHf93Mo8RQN0KOUuOn19P4oWNFWe5n2/She9N7eTo1gwVjAOBgNVHQ8BAf8EBAMCB4AwFQYDVR0lBA4wDAYKKwYBBAGD6F4CATAMBgNVHRMBAf8EAjAAMB8GA1UdIwQYMBaAFM5R4gSBTmRbI/jjxM+aPpzB11zCMAoGCCqGSM49BAMDA2cAMGQCMDFzHRSeAXrSy1WOzkbhPZ6Km2wGTmZ/2gK18k8BQGXyqz88Rdrz6CTX9flAnYNVxgIwcF9c3fVhqmJKpi+UhasNUMko69cyX6STPfta3Q8EjyzDjzoyrol46FP6VFHhvUcJoWNwYWRZDZ4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD2WEAI1vj4pqEmG47Dn/c1y2qZ6WO9zOv5NqgjLD69Q/OBV8Je7+REjv3otcVUIWjlzkLgajS+y2o8TF0TG7gFMBbnONDrsgAAAv1JREFUeJzt1s2rlVUUBvDf+bgmdyBRoTkJSagogihQA0UygqDoi+gfKIiMaFhgQtBAbOLAcJARUU2C6AOKBjXqc1BQ1KAgisrMLO3T9F69ntNgrc3Z973nvl4v9xKBC17es9+z9n7Wetaz196cs//YOovw71bzhhjke9mt2/Jfb7GLLpSBrsh0AptxRYL+hA9wONdaFiZK5lvxIX7DX/gHx/A1Hmz4LpkVarfgSIIfxR84gO9xCDN4dDmC6KCP9xL8FzyJ2/FNgh/AD/gTm3LOgjXRFm1X1PRaXInfMYm38LooQfEp/vfneMEstImwl4vdgHsT8C78jL+xDicrsJL5JnwnmDvtDMJsi7QjlD8lNHBLAl+I9ThlxMAwwfrYhw1CF8MzJDlvAP1c4Hq8gs+F+CYTeGrM3I5gaQPewC6xbVuDGBdAAd+Kd/CUyH5fBjBoWbCXQZzAw3ge56X/2DnNAAr4NiG2x/BE+h0zu57Daly/u/kcxp3YnUGPZbv+WMBvxpt4BHsygwEuM7vb1QHUZ0MZT2QQ9+FuI42MDaCX4LfhNUHfXiMlw4rqdzmAxrXfetwTzO3CmsSYxUSh6zTuEILbjqcrRoodMtqaddZ1bTuN7x2xVVdjP87XEGU5ZDbiZUHXsw3wQb7fF+qvj+QavC5JbT3RJbfhGVGaXplb6PgRN+E5o3IUKwL6RGhjdWZVZz2OgXr+AMdFK58x6hFznAsjTSsNZ63Y4+tFX1iR/5fsO9UzTKBV6TeFadFTdovzZVDXq2hhPivBXSLKtFmcD9MNBvrp1xdd8yV8Ktr4OqGDadyIz1rw5g2CqOMD+FKovNwPpnBQnJzfYmf6yoAux3UZSL9EvFi7Cq+KLXYKFwjaH8LbeBy/VuAzc5c4u8tD8b0H7+IjrMRFeFF0zuO4GF8IFiZEkjNGZe7VuHM6U4uVuk7iK3wsmtUq0el24Bq8IO4QV4sa1yfmkt0Zm8ytwaW4dakA2qxct7rVU9tZXckWa03x1vU9Z/8v+xcii8PJAgDDBAAAAABJRU5ErkJggg==';

export function createTray() {
  // 按 2x 载入，Retina 上是 16pt 的清晰剪影；template image 由 macOS 自动适配明暗模式
  const icon = nativeImage.createFromBuffer(Buffer.from(TRAY_ICON_BASE64, 'base64'), { scaleFactor: 2 });
  icon.setTemplateImage(true);

  tray = new Tray(icon);
  tray.setToolTip('TTY');

  updateTrayMenu();

  ipcMain.handle('get-config', () => getConfig());
  ipcMain.handle('save-config', (_event, config) => {
    const result = saveConfig(config);
    if (config.uiLanguage) { resetUILanguage(); updateTrayMenu(); }
    if (config.hotkey || config.dismissKey || config.cacheKey || config.regionKey || config.textKey || config.clipKey) {
      const { restartWithHotkeys } = require('./hotkey');
      restartWithHotkeys({
        trigger: result.hotkey,
        dismiss: result.dismissKey,
        cache: result.cacheKey,
        region: result.regionKey,
        text: result.textKey,
        clip: result.clipKey,
      });
    }
    if (Object.prototype.hasOwnProperty.call(config, 'openAtLogin')) {
      applyLoginItem(result.openAtLogin);
    }
    return result;
  });
  ipcMain.handle('resize-settings', (_event, contentHeight: number) => {
    if (settingsWin && !settingsWin.isDestroyed()) {
      const titleBarHeight = 28;
      const bounds = settingsWin.getBounds();
      settingsWin.setBounds(
        { x: bounds.x, y: bounds.y, width: bounds.width, height: contentHeight + titleBarHeight },
        true // animate on macOS
      );
    }
  });
}

export function updateTrayMenu() {
  if (!tray) return;
  const overlayVisible = isOverlayVisibleFn ? isOverlayVisibleFn() : false;

  const emptyIcon = nativeImage.createEmpty();
  const contextMenu = Menu.buildFromTemplate([
    {
      label: t('trayTranslate'),
      icon: emptyIcon,
      enabled: !overlayVisible,
      click: () => {
        if (onTranslateCallback) onTranslateCallback();
        setTimeout(() => updateTrayMenu(), 1000);
      },
    },
    {
      label: t('traySelectionTranslate'),
      icon: emptyIcon,
      click: () => { if (onSelectionTranslateCallback) onSelectionTranslateCallback(); },
    },
    {
      label: t('trayClipboardTranslate'),
      icon: emptyIcon,
      click: () => { if (onClipboardTranslateCallback) onClipboardTranslateCallback(); },
    },
    {
      label: t('trayHide'),
      icon: emptyIcon,
      enabled: overlayVisible,
      click: () => {
        if (onHideCallback) onHideCallback();
        setTimeout(() => updateTrayMenu(), 300);
      },
    },
    { type: 'separator' },
    {
      label: t('trayClearCache'),
      icon: emptyIcon,
      click: () => {
        if (onClearCacheCallback) onClearCacheCallback();
      },
    },
    {
      label: t('traySettings'),
      icon: emptyIcon,
      click: openSettings,
    },
    {
      label: t('trayQuit'),
      icon: emptyIcon,
      click: () => { app.quit(); },
    },
  ]);
  tray.setContextMenu(contextMenu);
}

export function openSettings() {
  if (settingsWin && !settingsWin.isDestroyed()) {
    settingsWin.focus();
    return;
  }

  settingsWin = new BrowserWindow({
    width: 480,
    height: 560,
    resizable: true,
    minimizable: false,
    title: t('settingsTitle'),
    webPreferences: {
      preload: path.join(__dirname, '..', 'preload', 'settings-preload.js'),
      contextIsolation: true,
      nodeIntegration: false,
    },
  });

  settingsWin.loadFile(path.join(app.getAppPath(), 'src', 'renderer', 'settings.html'));

  settingsWin.on('closed', () => {
    settingsWin = null;
  });
}
